#!/bin/bash
set -e
outargs=()

fail () { echo >&2 "stunt ld: $*"; exit 127; }

noshift () { fail "no arg for $a"; }

echo "stunt ld: $*"

unset march
while [ $# != 0 ]; do
	a=$1; shift
	case "$a" in
	# ignore lib(s) which may be insisted upon by the toolchain
	-lssp_nonshared)
		;;
	[^-]*|-L*|-l*|--whole-archive|--no-whole-archive|--start-group|--end-group)
		outargs+=("$a")
		;;
	-m)
		march="$1"; shift || noshift
		outargs+=("$a" "$march")
		;;
	-o)
        	outfile="$1"; shift || noshift
        	;;
	-z)
		outargs+=("$a" "$1"); shift || noshift
		;;
	-pie)
		;;
	--as-needed|--no-as-needed)
		;;
	--stunt-final-script)
		finallds="$1"; shift || noshift
		;;
	--stunt-intermediate)
        	inter1="$1"; shift || noshift
        	;;
	-plugin|-plugin-opt)
		shift || noshift
		;;
	-plugin-opt=*)
		;;
	*)
		fail "unknown option $a"
		;;
	esac
done

if [ x"$outfile" = x ]; then outfile=a.out; fi

set -x
ld -nostdlib -r "${outargs[@]}" -o "$inter1"
ld ${march:+-m ${march}} -T "$finallds" "$inter1" -o "$outfile"
