#!/bin/sh
#
# Copyright (c) 2014 Martin Lucina.  All Rights Reserved.
# Copyright (c) 2015 Antti Kantee.  All Rights Reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
# OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

#
# rumprun: "driver" script for running rumprun application stacks
#

# default values
MEM_DEFAULT=64

if [ "${RUMPRUN_WARNING_STFU}" != 'please' ]; then
	exec 3>&1 1>&2
	echo
	echo !!!
	echo !!! NOTE: rumprun is experimental and may change in the future
	echo !!!
	echo
	exec 1>&3 3>&-
fi

die ()
{

	echo rumprun: error: "$@" 1>&2
	exit 1
}

scriptopts='DhSt:T:'
guestopts='b:dD:e:iI:M:n:N:pW:'

# script option default values
DUMPCMD=
CANSUDO=false
PRESERVETMPDIR=false

usage ()
{

	cat <<EOM
usage: rumprun [script args] PLATFORM [guest args] APP [ -- ] [app args]

PLATFORM is the rumprun runtime platform to use
    iso  : bake app and config into a bootable iso image
    kvm  : baremetal guest via qemu -enable-kvm
    qemu : baremetal guest via qemu -no-kvm
    xen  : xen guest via xl(1)

APP is the binary to rumprun.  app args are processed by APP.

script args are:
	[-h] [-DS] [-t tmpdir] [-T tmpdir]

   -h display this message

   -D dump backend commands instead of running them
   -S execute sudo where potentially necessary
   -t use tmpdir as dir for temp files (default: /tmp/rumprun.XXXXXXXX)
   -T same as -t, except do not remove temporary directory

guest args are:
	[-dip] [-b blkspec] [-D port] [-e VAR[=VALUE]] [-I ifopts] [-M mem]
	[-N name] [-n netspec]

   -b configures a block device.  The format of "blkspec" is:
       hostpath[,mountpoint] where:
	hostpath   = image that is passed to the guest as a block device
	mountpoint = if "hostpath" is a file system image, mountpoint on guest
   -D attaches a gdb server on port to the guest
   -d destroys the guest on poweroff
   -e set environment VAR to VALUE
   -I create guest network interface and attach the user-specified
      iftag to it.  the format is:
	iftag,ifbasename,[,backendopts]
	e.g. -I 'qnet0,vioif,-net tap=/dev/tap0'
	(NOTE: currently available only for kvm/qemu)
   -i attaches to guest console on startup
   -M set the guest's memory to mem megabytes, default is ${MEM_DEFAULT}
   -N set the guest's name to name, default is rumprun-APP
   -n configures a network interface, where netspec is one of:
	inet,dhcp - IPv4 with DHCP
	inet,static,addr/mask[,gateway] - IPv4 with static IP
	inet6,auto - IPv6 with stateless autoconfiguration
   -p creates the guest but leaves it paused
   -W configure network interface new style
	iftag,type,method[,params]
	e.g. -W qnet0,inet,static,1.2.3.4/24
	(NOTE: currently available only for kvm/qemu)

EOM
	exit 1
}

nuketmpdir ()
{

	[ -z "${TMPDIR}" ] && return
	${PRESERVETMPDIR} && return

	realtmpdir="${TMPDIR}"
	TMPDIR=''
	rm -rf "${realtmpdir}"
}

setuptmpdir ()
{

	if [ -z "${TMPDIR}" ]; then
		TMPDIR=$(mktemp -d /tmp/rumprun.XXXXXXXX)
	else
		[ ! -d "${TMPDIR}" ] || die ${TMPDIR} already exists
		mkdir -p "${TMPDIR}" || die could not create ${TMPDIR}
		chmod 700 "${TMPDIR}" \
		    || { rm -rf "${TMPDIR}" ; die could not chmod ${TMPDIR}; }
	fi
	trap nuketmpdir 0 INT TERM
}

store_netspec=usage
store_blkspec=usage

nindex=0
bindex=0

createif_qemu ()
{
	local iftag ifbasename scratch qemuargs

	iftag="${1%%,*}"
	scratch="${1#*,}"
	ifbasename="${scratch%%,*}"
	qemuargs="${scratch#*,}"

	opt_netif="${opt_netif} -net nic,model=virtio ${qemuargs}"
	eval ${iftag}2ifname=${ifbasename}${nindex}
	nindex=$(expr $nindex + 1)
}

createif_iso ()
{
	local iftag
	local ifbasename

	iftag="${1%%,*}"
	ifbasename="${1#*,}"

	[ "${iftag}" != "${ifbasename}" ] || usage

	eval ${iftag}2ifname=${ifbasename}${nindex}

	nindex=$(expr $nindex + 1)
}

createif_xen ()
{
	local iftag
	local ifbasename

	iftag="${1%%,*}"
	ifbasename="${1#*,}"

	[ "${iftag}" != "${ifbasename}" ] || usage

	eval ${iftag}2ifname=${ifbasename}${nindex}
	eval ${iftag}2index=${nindex}

	nindex=$(expr $nindex + 1)

	# it's magic ;)
	conf_vif="${conf_vif}'',"
}

json_depth=0
json_indent ()
{

	for x in $(seq ${json_depth}); do
		printf '\t' >> ${TMPDIR}/json.cfg
	done
}

json_append_ln ()
{

	json_indent
	echo "$*, " >> ${TMPDIR}/json.cfg
}

json_open_block ()
{

	json_append_ln "${1:+\"$1\" : }" {
	json_depth=$((${json_depth}+1))
}

json_finalize_block ()
{

	[ ${json_depth} -ne 0 ] || die internal json error
	json_depth=$((${json_depth}-1))
	json_append_ln }
}

# Detect the filesystem type of the image at $1.
detect_fstype ()
{
	eval $(blkid -o export $1)
	if [ $? -ne 0 ]; then
		TYPE=unknown
	fi
	case ${TYPE} in
	ufs)
		echo ffs
		return 0
		;;
	iso9660)
		echo cd9660
		return 0
		;;
	*)
		echo unknown
		return 1
		;;
	esac
}

xen_store_netspec ()
{
	local index

	index=$(eval echo \${${iftag}2index})

	echo net/${index}/type ${iftype} >>${xenstore}
	echo net/${index}/method ${ifmethod} >>${xenstore}
	if [ -n "${ifaddr}" ]; then
		echo net/${index}/addr ${ifaddr} >>${xenstore}
		echo net/${index}/netmask ${ifmask} >>${xenstore}
	fi
	if [ -n "${ifgw}" ]; then
		echo net/${index}/gw ${ifgw} >>${xenstore}
	fi
}

json_store_netspec ()
{

	json_open_block net

	# XXX: should not assume vioif or -net user
	json_append_ln	'"if":		"'$(eval echo \${${iftag}2ifname})'"'
	json_append_ln	'"type":	"'${iftype}'"'
	json_append_ln	'"method":	"'${ifmethod}'"'

	[ -n "${ifaddr}" ] || { json_finalize_block ; return ; }

	json_append_ln	'"addr":	"'${ifaddr}'"'
	json_append_ln	'"mask":	"'${ifmask}'"'

	[ -n "${ifgw}" ] || { json_finalize_block ; return ; }

	json_append_ln	'"gw":		"'${ifgw}'"'

	json_finalize_block
}

parse_netspec ()
{
	iftag=$1
	shift

	IFS=,
	set -- $1
	unset IFS

	[ $# -lt 2 ] && usage
	iftype=$1
	ifmethod=$2
	[ "${iftype}" != "inet" -a "${iftype}" != "inet6" ] && return 1
	case ${ifmethod} in
		auto)
			;;
		dhcp)
			;;
		static)
			ifaddr=${3%/*}
			ifmask=${3#*/}
			[ -n "${ifaddr}" ] || usage
			[ -n "${ifmask}" ] || usage
			ifgw=$4
			;;
		*)
			return 1
			;;
	esac

	${store_netspec}

	return 0
}

parse_newnetspec ()
{

	iftag=${1%%,*}
	parse_netspec ${iftag} "${1#*,}"
}

xen_store_blkspec ()
{

	vdev=hd$(echo ${bindex} | tr '[0-9]' '[a-j]')
	conf_disk="${conf_disk}'file:$image,$vdev,w',"
	echo blk/${bindex}/type etfs >>${xenstore}
	echo blk/${bindex}/fstype $fstype >>${xenstore}
	if [ -n "$mountpoint" ]; then
		echo blk/${bindex}/mountpoint $mountpoint\
		>>${xenstore}
	fi
}

json_store_qemu_blkspec ()
{

	# XXX: should not generate the interface here
	opt_drivespec="${opt_drivespec} -drive if=virtio,file=${image}"

	# if the image does not need to be mounted, we're done
	[ -n "${mountpoint}" ] || return

	json_open_block blk

	# XXX: should not assume ld (virtio)
	json_append_ln	'"source":	"'dev'"'
	json_append_ln	'"path":	"'/dev/ld${bindex}a'"'
	json_append_ln	'"fstype":	"'${fstype}'"'
	json_append_ln	'"mountpoint":	"'${mountpoint}'"'

	json_finalize_block
}

json_store_iso_blkspec ()
{

	mkdir -p "${ISODIR}/images"

	# XXX: might have accidental clashes due to images from
	# many source subdirectories
	[ ! -f "${ISODIR}/images/$(basename ${image})" ] \
	    || die image \"${image}\" already exists in destdir
	cp ${image} "${ISODIR}/images/"

	# well, this is a bit questionable, but ...
	[ -n "${mountpoint}" ] || return

	json_open_block blk

	json_append_ln	'"source":	"'vnd'"'
	json_append_ln	'"path":	"'images/$(basename ${image})'"'
	json_append_ln	'"fstype":	"'${fstype}'"'
	json_append_ln	'"mountpoint":	"'${mountpoint}'"'

	json_finalize_block
}

parse_blkspec ()
{
	spec=$1

	image=${spec%,*}
	image=$(readlink -f ${image})
	mountpoint=$(echo ${spec} | sed -n 's/.*,\(.*\)/\1/p')
	[ -n "$image" ] || usage
	[ -f "$image" ] || die File $image does not exist

	if [ -n "$mountpoint" ]; then
		fstype=$(detect_fstype $image)
		[ $? -ne 0 ] && die File $image: unknown fstype
	fi

	${store_blkspec}
	bindex=$(expr $bindex + 1)
}

# run_xen: Generate Xen configuration and run application stack.
run_xen ()
{

	[ -z "${DUMPCMD}" ] || echo WARNING: -D not perfectly supported by Xen

	# try to find gdbsx from common locations
	unset gdbsx
	for x in gdbsx /usr/lib/xen-4.4/bin/gdbsx ; do
		if type ${x}> /dev/null 2>&1; then
			gdbsx="$x"
			break
		fi
	done

	store_blkspec=xen_store_blkspec
	store_netspec=xen_store_netspec

	conf="${TMPDIR}/xr.conf"
	xenstore="${TMPDIR}/xr.store"
	>${conf}
	>${xenstore}
	OPTIND=1
	conf_disk=
	conf_vif=
	opt_pause=
	opt_interactive=
	opt_destroy='on_poweroff="preserve"'
	opt_mem=${MEM_DEFAULT}
	opt_name=
	opt_debug=
	sudo=''

	while getopts "${guestopts}" opt; do
		case "$opt" in
		# -n: NETSPEC
		n)
			netname=_net${nindex}
			createif_xen ${netname},xenif || usage
			parse_newnetspec "${netname},${OPTARG}" || usage
			;;
		# -b: BLKSPEC: hostpath,mountpoint
		b)
			parse_blkspec "${OPTARG}" || usage
			;;
		# -e: Set guest environment variable.
		e)
			case "${OPTARG}" in
			*=*)
				key=${OPTARG%%=*}
				value=${OPTARG#*=}
				;;
			*)
				key=${OPTARG}
				value=
				;;
			esac
			[ -n "$key" ] || usage
			echo environ/${key} "${value}" >>${xenstore}
			;;
		# -p: Leave the domain paused after creation.
		p)
			opt_pause=1
			;;
		# -i: Attach to domain console on startup.
		i)
			opt_interactive=1
			;;
		# -I: create interface
		I)
			createif_xen "${OPTARG}" || usage
			;;
		# -d: Destroy domain on poweroff instead of preserving it.
		d)
			opt_destroy='on_poweroff="destroy"'
			;;
		# -N: Override domain name.
		N)
			opt_name=${OPTARG}
			;;
		# -M: Set domain memory.
		M)
			opt_mem=${OPTARG}
			;;
		# -D PORT: attach gdbsx to domain.
		D)
			if [ -z "${gdbsx}" ]; then
				die "'gdbsx' is required for -D, please install it."
			fi
			opt_debug=${OPTARG}
			;;
		W)
			parse_newnetspec "${OPTARG}" || usage
			;;
		*)
			usage
			;;
		esac
	done
	# Clean up vif and disk, xl does not like trailing commas.
	conf_vif=$(echo ${conf_vif} | sed -e s/,\$//)
	[ -n ${conf_vif} ] && conf_vif="vif=[${conf_vif}]"
	conf_disk=$(echo ${conf_disk} | sed -e s/,\$//)
	[ -n ${conf_disk} ] && conf_disk="disk=[${conf_disk}]"
	# Remaining arguments belong to the application.
	shift $((OPTIND-1))
	[ "$1" = "--" ] && shift
	[ $# -lt 1 ] && usage
	name=${opt_name:-rumprun-$(basename $1)}
	app=$(readlink -f $1)
	shift
	# Generate xl configuration file.
	cat <<EOM >"${TMPDIR}/xr.conf"
kernel="${app}"
name="${name}"
vcpus=1
memory=${opt_mem}
on_crash="preserve"
${opt_destroy}
extra="$@"
${conf_vif}
${conf_disk}
EOM
	if ${CANSUDO} && [ $(id -u) -ne 0 ]; then
		sudo='sudo'
	fi

	# Create the domain and leave it paused so that we can get its domid.
	if ! ${DUMPCMD} ${sudo} xl create -p ${conf} >/dev/null; then
		die xl create failed
	fi
	domid=$(${DUMPCMD} ${sudo} xl domid ${name})
	# Write provisioning information for domain to xenstore.
	prefix=/local/domain/${domid}/rumprun
	cat ${xenstore} | while read key value; do
		${DUMPCMD} ${sudo} xenstore-write "${prefix}/${key}" "${value}"
	done

	nuketmpdir

	# Attach debugger if requested.
	if [ -n "$opt_debug" ]; then
		if objdump -f ${app} | grep -q elf64; then
			bits=64
		else
			bits=32
		fi
		${DUMPCMD} ${gdbsx} -a ${domid} ${bits} ${opt_debug} &
	fi
	# Go go go!
	[ -z "$opt_pause" ] && ${DUMPCMD} ${sudo} xl unpause ${domid}
	if [ -n "$opt_interactive" ]; then
		${DUMPCMD} exec ${sudo} xl console $domid
	else
		echo xen:${domid}
	fi
}

run_qemu ()
{

	store_blkspec=json_store_qemu_blkspec
	store_netspec=json_store_netspec

	opt_interactive=
	opt_drivespec=
	opt_debug=
	opt_pause=
	opt_netif=
	opt_mem=${MEM_DEFAULT}

	json_open_block

	variant=$1
	shift
	while getopts "${guestopts}" opt; do
		case "$opt" in
		b)
			parse_blkspec "${OPTARG}" || usage
			;;
		d)
			die -d not supported on qemu/kvm
			;;
		D)
			opt_debug="-gdb tcp::${OPTARG}"
			;;
		e)
			json_append_ln "\"env\": \"${OPTARG}\""
			;;
		i)
			opt_interactive=1
			;;
		I)
			createif_qemu "${OPTARG}" || usage
			nindex=$(expr $nindex + 1)
			;;
		M)
			opt_mem=${OPTARG}
			;;
		n)
			netname=_net${nindex}
			createif_qemu "${netname},-net user"
			parse_netspec ${netname} "${OPTARG}" || usage
			;;
		N)
			# ignored
			opt_name=${OPTARG}
			;;
		p)
			opt_pause="-S"
			;;
		W)
			parse_newnetspec "${OPTARG}" || usage
			;;
		*)
			usage
			;;
		esac
	done
	shift $((${OPTIND}-1))

	if [ "${variant}" = "kvm" ]; then
		opt_kvm=-enable-kvm
	else
		opt_kvm=-no-kvm
	fi

	json_append_ln "\"cmdline\": \""$@"\""
	json_finalize_block

	# internal check
	[ ${json_depth} -eq 0 ] || die internal error, final depth ${json_depth}

	json_coma="$(sed 's/,/,,/g' < "${TMPDIR}/json.cfg")"

	[ -n "${opt_netif}" ] || opt_netif="-net none"

	qemucmd="${DUMPCMD} qemu-system-i386 ${opt_netif} ${opt_kvm}	\
	    ${opt_drivespec} ${opt_debug} ${opt_pause} -m ${opt_mem}	\
	    -kernel $1"
	if [ -n "$opt_interactive" ]; then
		${qemucmd} -append "${json_coma}"
	else
		qemucmd="${qemucmd} -display none"
		${qemucmd} -append "${json_coma}" 1>/dev/null 2>&1 &
		echo qemu:$!
	fi
}

bake_iso ()
{

	type xorriso >/dev/null || die bake_iso needs xorriso
	type grub-mkrescue >/dev/null || die bake_iso needs grub-mkrescue

	store_blkspec=json_store_iso_blkspec
	store_netspec=json_store_netspec

	opt_interactive=
	opt_drivespec=
	opt_debug=
	opt_pause=
	opt_netif=
	opt_mem=${MEM_DEFAULT}

	blk_specified=false

	ISODIR="${TMPDIR}/iso"
	mkdir -p "${ISODIR}"

	json_open_block

	while getopts "${guestopts}" opt; do
		case "$opt" in
		b)
			${blk_specified} \
			    && die only one -b parameter supported.  will fix.
			blk_specified=true
			parse_blkspec "${OPTARG}" || usage
			;;
		d)
			die -d not supported on iso
			;;
		D)
			die -D not supported on iso
			;;
		e)
			json_append_ln "\"env\": \"${OPTARG}\""
			;;
		i)
			die -i not supported on iso
			;;
		I)
			createif_iso "${OPTARG}" || usage
			nindex=$(expr $nindex + 1)
			;;
		M)
			die -M not supported on iso
			;;
		N)
			opt_name=${OPTARG}
			;;
		p)
			die -p not supported on iso
			;;
		W)
			parse_newnetspec "${OPTARG}" || usage
			;;
		*)
			usage
			;;
		esac
	done
	shift $((${OPTIND}-1))
	bootimage=$1
	: ${opt_name:=rumprun-$(echo ${bootimage} | tr / _).iso}

	[ ! -f ${opt_name} ] || die target ${opt_name} already exists

	json_append_ln "\"cmdline\": \""$@"\""
	json_finalize_block
	[ ${json_depth} -eq 0 ] || die internal error, final depth ${json_depth}

	# create the iso directory structure
	mkdir -p "${ISODIR}/boot/grub"
	printf 'set timeout=0\n' > "${ISODIR}/boot/grub/grub.cfg"
	printf 'menuentry "rumpkernel" {\n' >> "${ISODIR}/boot/grub/grub.cfg"
	printf '\tmultiboot /boot/%s ROOTFSCFG=/json.cfg\n}\n' $(basename $1) \
	    >> "${ISODIR}/boot/grub/grub.cfg"
	cp ${bootimage} "${ISODIR}/boot"
	cp "${TMPDIR}/json.cfg" "${ISODIR}"
	grub-mkrescue "${ISODIR}" -o ${opt_name}
}

if [ $# -lt 2 ]; then
	usage
fi

while getopts "${scriptopts}" opt; do
	case "${opt}" in
	D)
		DUMPCMD=echo
		;;
	h)
		usage
		;;
	S)
		CANSUDO=true
		;;
	t)
		TMPDIR="${OPTARG}"
		;;
	T)
		PRESERVETMPDIR=true
		TMPDIR="${OPTARG}"
		;;
	esac
done
shift $((${OPTIND}-1))
OPTIND=1

platform="$1"
shift

setuptmpdir

case ${platform} in
xen)
	run_xen "$@"
	;;
iso)
	bake_iso "$@"
	;;
kvm)
	run_qemu kvm "$@"
	;;
qemu)
	run_qemu qemu "$@"
	;;
*)
	echo Invalid platform \"${platform}\" 1>&2
	usage
	;;
esac

exit 0
