PCIDIR:= ${.PARSEDIR}

.include "${RUMPRUN_MKCONF}"
.include "${BUILDRUMP_TOOLFLAGS}"

PCI_HYPERCALLS=		rumppci.c rumpdma.c
PCI_HYPERCALLS_PATH:=	${PCIDIR}
PCI_CPPFLAGS:=		-I${PCIDIR}/../include

.include "${PCIDIR}/../../../lib/Makefile.pcicommon"
