PCIDIR!=	cd ${.PARSEDIR} ; pwd -P

.include "${RUMPRUN_MKCONF}"
.include "${BUILDRUMP_TOOLFLAGS}"

PCI_HYPERCALLS=		rumphyper_pci.c rumphyper_dma.c
PCI_HYPERCALLS_PATH:=	${PCIDIR}
PCI_CPPFLAGS:=		-I${PCIDIR}/../xen/include

.include "${PCIDIR}/../../../lib/Makefile.pcicommon"
